### ISSUE TITLE
Sass processing in siteleaf

### ISSUE THREAD

**Issue by johnchourajr** [siteleaf/siteleaf-gem#22]
I'd love to start using SASS with my Siteleaf site. I've installed the Sass gem, but how can I install a sass processor for my site's repository? Thanks in advance!

**Comment by jdsimcoe** [comment]
@sskylar or @larryfox I'm having issues with my Guardfile:

```ruby
guard 'sass', :output => 'styles/css', :all_on_start => true, :style => :compressed do
  watch %r{styles/(.+\.sass)$}
end

guard 'coffeescript', :input => 'scripts/coffee', :output => 'scripts/js' do
  watch(%r{scripts/(.+\.coffee)})
end

guard 'livereload' do
  watch(%r{scripts/js/min/.+\.(css|js|html)})
  watch(%r{styles/css/.+\.(css|js|html)})
end
```

I started with @sawyerh's solution but modified it because the `SCSS` and `CoffeeScript` stuff wasn't compiling when I ran `bundle exec guard`. My modified code above, some borrowed from @destroytoday seems to sort of work. When I save the `.coffee` file it gives me this output:

```log
22:39:22 - INFO - Compile scripts/coffee/global.coffee
22:39:22 - INFO - 10:39:22 PM Successfully generated 
```

But it doesn't actually generate a `.js` file in **scripts/js**. Any idea what I am missing here?

**Comment by sskylar** [comment]
@jdsimcoe For Guard help please see http://stackoverflow.com/questions/tagged/guard

**Comment by jdsimcoe** [comment]
Thanks @sskylar found that the latest `guard-coffeescript` method is to supply a `patterns` option. It silently fails without this:

```ruby
# Compile Coffeescript
coffeescript_options = {
  input: 'scripts',
  output: 'scripts/js',
  patterns: [%r{scripts/(.*)\.coffee$}]
}

guard 'coffeescript', coffeescript_options do
  coffeescript_options[:patterns].each { |pattern| watch(pattern) }
end
```
That worked for me. Feel free to use it or not. Just an FYI I guess.
