### ISSUE TITLE
Expect failed publish to exit with an error code

### ISSUE THREAD

**Issue by barnabyalter** [siteleaf/siteleaf-gem#68]
@sskylar Occasionally publishing will error out with a message similar to the following:

```
Publish error: POST https://api.github.com/repos/NYULibraries/library.nyu.edu/git/trees: 405 - <html>
 <head><title>405 Not Allowed</title></head>
 <body bgcolor="white">
 <center><h1>405 Not Allowed</h1></center>
 <hr><center>nginx</center>
 </body>
 </html>
=> Publish completed.
```

However, if I am publishing in a flow on a CI system (for instance Jenkins) this is not seen as a failure because the job ends with a success message. If the job fails I would expect it to end with an error code.

**Comment by ericgriffis** [comment]
+1

We're experiencing this issue with 404 errors:

```
+ bundle exec siteleaf publish
Not Found
=> Publish completed.
```

Upon further inspection the API is responding with a 404 error. This was evidently happening for quite some time, but since the gem silences the error and returns success, we had no way of knowing our site was not publishing without user intervention. 

I would expect the job to return an error code when its not successful – any reason this can't happen?

**Comment by sskylar** [comment]
@ericgriffis Can you tell me the output from `bundle exec siteleaf -v`?

**Comment by ericgriffis** [comment]
@sskylar Same output with `-v` option.

The [`id` attribute](https://github.com/siteleaf/siteleaf-gem/blob/master/lib/siteleaf/job.rb#L4) on the job instance is `nil`, which seems to be causing the 404 response. This apparently happens because the [response from publish](https://github.com/siteleaf/siteleaf-gem/blob/master/lib/siteleaf/site.rb#L42) is 400 Bad request – "Site is not publishable".

It would be much clearer if the gem simply raised these error responses.

**Comment by sskylar** [comment]
@ericgriffis Sorry for the confusion. When you run `bundle exec siteleaf -v` you should see a version number. Can you let me know what it says?

**Comment by ericgriffis** [comment]
@sskylar `2.0.0`

**Comment by ericgriffis** [comment]
@sskylar Didn't see your second question – we had setup hosting and it was publishing successfully up until a few days ago.

**Comment by GregJacobs82** [comment]
^bump

**Comment by sskylar** [comment]
Starting with 2.1.0, the CLI will return an appropriate exit code on error.
